server:
  port: 8082
  servlet.context-path: /api-gestion-academica

spring:
  application:
    name: api-pedidos

  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    open-in-view: false
    show-sql: true
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:db_academica}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: always

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:6082/realms/REALM_DEMO_V1/protocol/openid-connect/certs

keycloak:
  resource: api-gestion-academica
