server:
  port: 8082
  servlet.context-path: /api-gestion-academica

spring:
  application:
    name: api-pedidos

  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/db_academica?createDatabaseIfNotExist=true&useSSL=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: always

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:6082/realms/REALM_DEMO_V1/protocol/openid-connect/certs

keycloak:
  resource: api-gestion-academica
