#!/usr/bin/env bash
set -euo pipefail

# App DB connection (aligned with application.yml defaults).
DB_HOST="${DB_HOST:-localhost}"
DB_PORT="${DB_PORT:-5432}"
DB_NAME="${DB_NAME:-db_academica}"
DB_USERNAME="${DB_USERNAME:-postgres}"
DB_PASSWORD="${DB_PASSWORD:?set DB_PASSWORD}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
DATA_SQL="${PROJECT_ROOT}/src/main/resources/data.sql"

if [[ ! -f "${DATA_SQL}" ]]; then
  echo "[seed] No se encontro data.sql en ${DATA_SQL}" >&2
  exit 1
fi

export PGPASSWORD="${DB_PASSWORD}"
PSQL=(psql -h "${DB_HOST}" -p "${DB_PORT}" -U "${DB_USERNAME}" -d "${DB_NAME}" -v ON_ERROR_STOP=1)

echo "[seed] Asegurando tabla tbl_company..."
"${PSQL[@]}" <<'SQL'
CREATE TABLE IF NOT EXISTS tbl_company (
  company_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company VARCHAR(260),
  contact VARCHAR(160),
  country VARCHAR(120),
  state VARCHAR(1)
);
SQL

echo "[seed] Limpiando datos previos de tbl_company..."
"${PSQL[@]}" -c "TRUNCATE TABLE tbl_company RESTART IDENTITY;"

echo "[seed] Cargando datos desde ${DATA_SQL}..."
"${PSQL[@]}" -f "${DATA_SQL}"

echo "[seed] OK: datos cargados en ${DB_NAME}."
